// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: parser.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParserService_ConvertDocument_FullMethodName = "/parser.ParserService/ConvertDocument"
	ParserService_ConvertURL_FullMethodName      = "/parser.ParserService/ConvertURL"
)

// ParserServiceClient is the client API for ParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ParserService is stateless. No state is retained after a stream closes.
type ParserServiceClient interface {
	// ConvertDocument streams file bytes from the caller and streams results back.
	ConvertDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConvertChunk, ConvertResult], error)
	// ConvertURL fetches a document from a URL and streams results back.
	ConvertURL(ctx context.Context, in *ConvertURLRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConvertResult], error)
}

type parserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParserServiceClient(cc grpc.ClientConnInterface) ParserServiceClient {
	return &parserServiceClient{cc}
}

func (c *parserServiceClient) ConvertDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConvertChunk, ConvertResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ParserService_ServiceDesc.Streams[0], ParserService_ConvertDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConvertChunk, ConvertResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParserService_ConvertDocumentClient = grpc.BidiStreamingClient[ConvertChunk, ConvertResult]

func (c *parserServiceClient) ConvertURL(ctx context.Context, in *ConvertURLRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConvertResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ParserService_ServiceDesc.Streams[1], ParserService_ConvertURL_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConvertURLRequest, ConvertResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParserService_ConvertURLClient = grpc.ServerStreamingClient[ConvertResult]

// ParserServiceServer is the server API for ParserService service.
// All implementations must embed UnimplementedParserServiceServer
// for forward compatibility.
//
// ParserService is stateless. No state is retained after a stream closes.
type ParserServiceServer interface {
	// ConvertDocument streams file bytes from the caller and streams results back.
	ConvertDocument(grpc.BidiStreamingServer[ConvertChunk, ConvertResult]) error
	// ConvertURL fetches a document from a URL and streams results back.
	ConvertURL(*ConvertURLRequest, grpc.ServerStreamingServer[ConvertResult]) error
	mustEmbedUnimplementedParserServiceServer()
}

// UnimplementedParserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParserServiceServer struct{}

func (UnimplementedParserServiceServer) ConvertDocument(grpc.BidiStreamingServer[ConvertChunk, ConvertResult]) error {
	return status.Error(codes.Unimplemented, "method ConvertDocument not implemented")
}
func (UnimplementedParserServiceServer) ConvertURL(*ConvertURLRequest, grpc.ServerStreamingServer[ConvertResult]) error {
	return status.Error(codes.Unimplemented, "method ConvertURL not implemented")
}
func (UnimplementedParserServiceServer) mustEmbedUnimplementedParserServiceServer() {}
func (UnimplementedParserServiceServer) testEmbeddedByValue()                       {}

// UnsafeParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserServiceServer will
// result in compilation errors.
type UnsafeParserServiceServer interface {
	mustEmbedUnimplementedParserServiceServer()
}

func RegisterParserServiceServer(s grpc.ServiceRegistrar, srv ParserServiceServer) {
	// If the following call panics, it indicates UnimplementedParserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParserService_ServiceDesc, srv)
}

func _ParserService_ConvertDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ParserServiceServer).ConvertDocument(&grpc.GenericServerStream[ConvertChunk, ConvertResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParserService_ConvertDocumentServer = grpc.BidiStreamingServer[ConvertChunk, ConvertResult]

func _ParserService_ConvertURL_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConvertURLRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParserServiceServer).ConvertURL(m, &grpc.GenericServerStream[ConvertURLRequest, ConvertResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParserService_ConvertURLServer = grpc.ServerStreamingServer[ConvertResult]

// ParserService_ServiceDesc is the grpc.ServiceDesc for ParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.ParserService",
	HandlerType: (*ParserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConvertDocument",
			Handler:       _ParserService_ConvertDocument_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ConvertURL",
			Handler:       _ParserService_ConvertURL_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parser.proto",
}
