// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: parser.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConvertChunk is sent by the caller (Go UI) to the parser.
// The first message must be a ConvertMeta, followed by one or more data messages.
type ConvertChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConvertChunk_Meta
	//	*ConvertChunk_Data
	Payload       isConvertChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertChunk) Reset() {
	*x = ConvertChunk{}
	mi := &file_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertChunk) ProtoMessage() {}

func (x *ConvertChunk) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertChunk.ProtoReflect.Descriptor instead.
func (*ConvertChunk) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertChunk) GetPayload() isConvertChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConvertChunk) GetMeta() *ConvertMeta {
	if x != nil {
		if x, ok := x.Payload.(*ConvertChunk_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *ConvertChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ConvertChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isConvertChunk_Payload interface {
	isConvertChunk_Payload()
}

type ConvertChunk_Meta struct {
	Meta *ConvertMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type ConvertChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ConvertChunk_Meta) isConvertChunk_Payload() {}

func (*ConvertChunk_Data) isConvertChunk_Payload() {}

type ConvertMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                    // original filename, used to infer format
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // caller-assigned correlation id; surfaced in parser logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMeta) Reset() {
	*x = ConvertMeta{}
	mi := &file_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMeta) ProtoMessage() {}

func (x *ConvertMeta) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMeta.ProtoReflect.Descriptor instead.
func (*ConvertMeta) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertMeta) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConvertMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ConvertResult is streamed back by the parser.
// StatusUpdate messages arrive before and after the markdown chunks.
type ConvertResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConvertResult_Status
	//	*ConvertResult_MarkdownChunk
	Payload       isConvertResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResult) Reset() {
	*x = ConvertResult{}
	mi := &file_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResult) ProtoMessage() {}

func (x *ConvertResult) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResult.ProtoReflect.Descriptor instead.
func (*ConvertResult) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{2}
}

func (x *ConvertResult) GetPayload() isConvertResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConvertResult) GetStatus() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ConvertResult_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ConvertResult) GetMarkdownChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ConvertResult_MarkdownChunk); ok {
			return x.MarkdownChunk
		}
	}
	return nil
}

type isConvertResult_Payload interface {
	isConvertResult_Payload()
}

type ConvertResult_Status struct {
	Status *StatusUpdate `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type ConvertResult_MarkdownChunk struct {
	MarkdownChunk []byte `protobuf:"bytes,2,opt,name=markdown_chunk,json=markdownChunk,proto3,oneof"`
}

func (*ConvertResult_Status) isConvertResult_Payload() {}

func (*ConvertResult_MarkdownChunk) isConvertResult_Payload() {}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // PROCESSING | DONE | FAILED
	PagesDone     int32                  `protobuf:"varint,2,opt,name=pages_done,json=pagesDone,proto3" json:"pages_done,omitempty"`
	PagesTotal    int32                  `protobuf:"varint,3,opt,name=pages_total,json=pagesTotal,proto3" json:"pages_total,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`     // received | loading | processing | exporting
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"` // human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusUpdate) GetPagesDone() int32 {
	if x != nil {
		return x.PagesDone
	}
	return 0
}

func (x *StatusUpdate) GetPagesTotal() int32 {
	if x != nil {
		return x.PagesTotal
	}
	return 0
}

func (x *StatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StatusUpdate) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_parser_proto protoreflect.FileDescriptor

const file_parser_proto_rawDesc = "" +
	"\n" +
	"\fparser.proto\x12\x06parser\"Z\n" +
	"\fConvertChunk\x12)\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.parser.ConvertMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"H\n" +
	"\vConvertMeta\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"s\n" +
	"\rConvertResult\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x14.parser.StatusUpdateH\x00R\x06status\x12'\n" +
	"\x0emarkdown_chunk\x18\x02 \x01(\fH\x00R\rmarkdownChunkB\t\n" +
	"\apayload\"\xac\x01\n" +
	"\fStatusUpdate\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"pages_done\x18\x02 \x01(\x05R\tpagesDone\x12\x1f\n" +
	"\vpages_total\x18\x03 \x01(\x05R\n" +
	"pagesTotal\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2S\n" +
	"\rParserService\x12B\n" +
	"\x0fConvertDocument\x12\x14.parser.ConvertChunk\x1a\x15.parser.ConvertResult(\x010\x01B7Z5github.com/GustavoCaso/folio/ui/internal/parser/protob\x06proto3"

var (
	file_parser_proto_rawDescOnce sync.Once
	file_parser_proto_rawDescData []byte
)

func file_parser_proto_rawDescGZIP() []byte {
	file_parser_proto_rawDescOnce.Do(func() {
		file_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parser_proto_rawDesc), len(file_parser_proto_rawDesc)))
	})
	return file_parser_proto_rawDescData
}

var file_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_parser_proto_goTypes = []any{
	(*ConvertChunk)(nil),  // 0: parser.ConvertChunk
	(*ConvertMeta)(nil),   // 1: parser.ConvertMeta
	(*ConvertResult)(nil), // 2: parser.ConvertResult
	(*StatusUpdate)(nil),  // 3: parser.StatusUpdate
}
var file_parser_proto_depIdxs = []int32{
	1, // 0: parser.ConvertChunk.meta:type_name -> parser.ConvertMeta
	3, // 1: parser.ConvertResult.status:type_name -> parser.StatusUpdate
	0, // 2: parser.ParserService.ConvertDocument:input_type -> parser.ConvertChunk
	2, // 3: parser.ParserService.ConvertDocument:output_type -> parser.ConvertResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parser_proto_init() }
func file_parser_proto_init() {
	if File_parser_proto != nil {
		return
	}
	file_parser_proto_msgTypes[0].OneofWrappers = []any{
		(*ConvertChunk_Meta)(nil),
		(*ConvertChunk_Data)(nil),
	}
	file_parser_proto_msgTypes[2].OneofWrappers = []any{
		(*ConvertResult_Status)(nil),
		(*ConvertResult_MarkdownChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parser_proto_rawDesc), len(file_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parser_proto_goTypes,
		DependencyIndexes: file_parser_proto_depIdxs,
		MessageInfos:      file_parser_proto_msgTypes,
	}.Build()
	File_parser_proto = out.File
	file_parser_proto_goTypes = nil
	file_parser_proto_depIdxs = nil
}
